import {
  MembershipPlan,
  PlanFeature,
  GymClass,
  Trainer,
  TransformationCase,
  GymLocation,
  Product,
  Lead,
  User,
  PRRecord,
  WeightLog,
  ClassBooking,
  NotificationItem,
} from './types';

export const INITIAL_USER: User = {
  id: 'user-01',
  name: 'Alex Morgan',
  email: 'alex.morgan@elitefit.club',
  phone: '+91 98301 23456',
  role: 'member',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  membershipPlan: 'Elite',
  membershipStatus: 'Active',
  membershipExpires: '2026-10-24',
  joinedDate: '2025-01-15',
  homeBranch: 'Kolkata Flagship (Park Street)',
  qrPassCode: 'EF-8924-KOL-ELITE',
  stats: {
    weeklyWorkouts: 4,
    weeklyClasses: 3,
    weeklyCalories: 2840,
    streakDays: 14,
    totalCheckins: 148,
  },
};

export const INITIAL_ADMIN_USER: User = {
  id: 'admin-01',
  name: 'Marcus Vance',
  email: 'marcus.vance@elitefit.club',
  phone: '+91 98300 11223',
  role: 'admin',
  avatar: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=400&q=80',
  membershipPlan: 'VIP',
  membershipStatus: 'Active',
  membershipExpires: '2030-01-01',
  joinedDate: '2023-04-01',
  homeBranch: 'Kolkata Flagship (Park Street)',
  qrPassCode: 'EF-ADMIN-001',
  stats: {
    weeklyWorkouts: 6,
    weeklyClasses: 5,
    weeklyCalories: 4200,
    streakDays: 45,
    totalCheckins: 620,
  },
};

export const MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: 'basic',
    name: 'BASIC',
    tagline: 'Foundational strength and conditioning access',
    priceMonthly: 1499,
    priceAnnualMonthly: 1199,
    color: '#9CA3AF',
    description: 'Perfect for disciplined self-starters seeking full access to world-class strength floors and cardio zones.',
    targetAudience: 'Independent lifters & fitness enthusiasts',
    features: [
      'Full access to primary gym floor & free weights',
      'Cardio & functional turf training zones',
      'Locker room & high-pressure shower access',
      'EliteFit Mobile App & Digital QR Pass',
      '1 Free Body Composition Scan per quarter',
      'Standard opening hours (06:00 AM - 10:00 PM)',
    ],
    limitations: [
      'Studio group classes not included',
      'No guest passes',
      'Single branch access only',
    ],
  },
  {
    id: 'pro',
    name: 'PRO',
    tagline: 'High-intensity coaching and all-studio class privileges',
    priceMonthly: 2499,
    priceAnnualMonthly: 1999,
    badge: 'MOST POPULAR',
    isPopular: true,
    color: '#E2F163',
    description: 'The definitive athlete package. Full club access, unlimited high-energy studio classes, and sauna recovery suites.',
    targetAudience: 'Dedicated athletes & group fitness lovers',
    features: [
      'Everything in Basic tier',
      'Unlimited Studio Classes (HIIT, Boxing, CrossFit, Yoga)',
      'Multi-branch access across all 4 cities',
      'Finnish dry sauna & steam room access',
      'Monthly InBody 570 body composition analysis',
      '2 Complimentary Guest Passes per month',
      '10% discount at the EliteFit Pro Store',
      'Extended hours access (05:00 AM - 11:00 PM)',
    ],
  },
  {
    id: 'elite',
    name: 'ELITE',
    tagline: 'The ultimate pinnacle of athletic luxury and recovery',
    priceMonthly: 3999,
    priceAnnualMonthly: 3199,
    badge: 'UNLIMITED LUXURY',
    color: '#D4AF37',
    description: 'Zero compromises. Unlimited club privileges, priority class bookings, recovery cryotherapy, and personal nutrition coaching.',
    targetAudience: 'High performers, executives & serious lifters',
    features: [
      'Everything in Pro tier with VIP privileges',
      'Priority 48-hour advance class booking window',
      'Cold plunge & infrared recovery suite access',
      'Permanent executive locker & fresh towel service',
      'Bi-weekly 1-on-1 PT consultation session',
      'Custom macro & sports nutrition blueprint',
      'Unlimited guest passes (1 guest per visit)',
      '20% off all Pro Store apparel & supplements',
      'Exclusive access to Hyrox & Lifting workshops',
    ],
  },
  {
    id: 'pt',
    name: 'PERSONAL TRAINING',
    tagline: '1-on-1 bespoke coaching engineered around your goals',
    priceMonthly: 7999,
    priceAnnualMonthly: 6499,
    badge: 'BESPOKE 1-ON-1',
    color: '#FF334B',
    description: 'Dedicated mentorship from CSCS certified master coaches. Biomechanical assessment, progressive overload, and 24/7 accountability.',
    targetAudience: 'Transformations, athletes, injury rehab',
    features: [
      'Includes Full ELITE Membership tier benefits',
      '12 Dedicated 1-on-1 60-min personal coaching sessions/month',
      'Biomechanical movement screen & posture analysis',
      'Weekly progressive overload & volume programming',
      'Daily 24/7 WhatsApp nutrition accountability',
      'Pre-workout and post-workout supplementation protocol',
      'Quarterly DEXA body composition scan',
    ],
  },
];

export const PLAN_COMPARISON_MATRIX: PlanFeature[] = [
  { name: 'Gym Floor & Free Weights Access', basic: true, pro: true, elite: true, pt: true, category: 'Access' },
  { name: 'Multi-Branch City Access', basic: 'Single Branch', pro: 'All 4 Branches', elite: 'All 4 Branches', pt: 'All 4 Branches', category: 'Access' },
  { name: 'Extended Operating Hours (5am-11pm)', basic: false, pro: true, elite: true, pt: true, category: 'Access' },
  { name: 'Unlimited Studio Classes (HIIT, Boxing, Yoga)', basic: false, pro: true, elite: true, pt: true, category: 'Coaching' },
  { name: 'Priority Class Booking Window', basic: false, pro: '24 Hours', elite: '48 Hours', pt: 'VIP Auto-Reserve', category: 'Coaching' },
  { name: '1-on-1 Personal Trainer Sessions', basic: false, pro: false, elite: 'Bi-weekly Check-in', pt: '12 Sessions/Mo', category: 'Coaching' },
  { name: 'Nutrition & Macro Protocol Blueprint', basic: false, pro: 'Standard Guide', elite: 'Custom Plan', pt: 'Daily 24/7 Coaching', category: 'Coaching' },
  { name: 'Dry Sauna & Steam Room', basic: false, pro: true, elite: true, pt: true, category: 'Amenities' },
  { name: 'Cold Plunge & Cryo Recovery Suite', basic: false, pro: false, elite: true, pt: true, category: 'Amenities' },
  { name: 'Permanent Locker & Towel Service', basic: false, pro: false, elite: true, pt: true, category: 'Amenities' },
  { name: 'InBody Body Composition Scans', basic: 'Quarterly', pro: 'Monthly', elite: 'Bi-weekly', pt: 'Weekly + DEXA', category: 'Amenities' },
  { name: 'Complimentary Guest Passes', basic: false, pro: '2 / month', elite: 'Unlimited (1/visit)', pt: 'Unlimited (2/visit)', category: 'Perks' },
  { name: 'EliteFit Store Merch Discount', basic: false, pro: '10% Off', elite: '20% Off', pt: '25% Off', category: 'Perks' },
  { name: 'EliteFit AI Smart Coach Access', basic: true, pro: true, elite: true, pt: true, category: 'Perks' },
];

export const TRAINERS: Trainer[] = [
  {
    id: 'alex-morgan',
    name: 'Alex Morgan',
    role: 'Head of Strength & Conditioning',
    experienceYears: 8,
    rating: 4.98,
    reviewCount: 142,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80',
    bio: 'Former national decathlete and CSCS coach specializing in maximum power output, athletic hypertrophy, and biomechanical optimization.',
    philosophy: 'Strength is not an accident. It is the predictable outcome of ruthless consistency, progressive overload, and unwavering intent.',
    certifications: ['NSCA-CSCS Certified', 'USA Weightlifting L2', 'EXOS Performance Specialist', 'Precision Nutrition L2'],
    specialties: ['Athletic Performance', 'Barbell Strength', 'Fat Loss & Recomp', 'Hyrox Prep'],
    instagram: '@alexmorgan_performance',
    classesTaught: ['HIIT Inferno', 'Iron & Hypertrophy', 'Functional Turf Conditioning'],
    availableSlots: [
      { day: 'Monday', times: ['07:00 AM', '09:00 AM', '05:00 PM', '06:30 PM'] },
      { day: 'Wednesday', times: ['08:00 AM', '10:00 AM', '04:00 PM', '07:00 PM'] },
      { day: 'Friday', times: ['07:00 AM', '11:00 AM', '05:00 PM', '06:00 PM'] },
      { day: 'Saturday', times: ['09:00 AM', '11:00 AM', '02:00 PM'] },
    ],
  },
  {
    id: 'elena-rostova',
    name: 'Elena Rostova',
    role: 'Master Boxing & Combat Coach',
    experienceYears: 10,
    rating: 4.95,
    reviewCount: 189,
    avatar: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1549476464-37392f717541?auto=format&fit=crop&w=1200&q=80',
    bio: 'Golden Gloves champion and elite conditioning specialist. Elena blends authentic pugilistic footwork with relentless metabolic conditioning.',
    philosophy: 'Boxing reveals who you are under fatigue. When your lungs burn, discipline is the only thing standing between victory and defeat.',
    certifications: ['AIBA Certified Boxing Coach', 'NASM-PES', 'TRX Master Instructor'],
    specialties: ['Championship Boxing', 'Metabolic Conditioning', 'Agility & Footwork', 'Mental Toughness'],
    instagram: '@elena_boxing_elite',
    classesTaught: ['Championship Boxing', 'HIIT Inferno'],
    availableSlots: [
      { day: 'Tuesday', times: ['06:30 AM', '08:30 AM', '06:00 PM', '07:30 PM'] },
      { day: 'Thursday', times: ['06:30 AM', '09:00 AM', '05:30 PM', '07:00 PM'] },
      { day: 'Saturday', times: ['08:00 AM', '10:00 AM', '01:00 PM'] },
    ],
  },
  {
    id: 'marcus-vance',
    name: 'Marcus Vance',
    role: 'CrossFit L3 & Hyrox Director',
    experienceYears: 9,
    rating: 4.97,
    reviewCount: 215,
    avatar: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=1200&q=80',
    bio: 'Hyrox Pro competitor and gymnastics specialist. Marcus has trained over 400 athletes for high-capacity hybrid athletic competitions.',
    philosophy: 'Engine beats ego every single time. Build a cardiovascular threshold that outlasts anyone in the room.',
    certifications: ['CrossFit Level 3 (CCMT)', 'Hyrox Master Coach', 'FMS Level 2'],
    specialties: ['CrossFit & Gymnastics', 'Hyrox Racing', 'Kettlebell Mastery', 'Aerobic Capacity'],
    instagram: '@marcus_vance_crossfit',
    classesTaught: ['Hyrox Athletic Prep', 'Functional Turf Conditioning'],
    availableSlots: [
      { day: 'Monday', times: ['06:00 AM', '08:00 AM', '06:00 PM'] },
      { day: 'Wednesday', times: ['06:00 AM', '07:30 AM', '05:30 PM'] },
      { day: 'Friday', times: ['06:00 AM', '08:30 AM', '05:00 PM'] },
    ],
  },
  {
    id: 'chloe-bennett',
    name: 'Chloe Bennett',
    role: 'Mobility & Vinyasa Lead',
    experienceYears: 7,
    rating: 4.99,
    reviewCount: 164,
    avatar: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80',
    bio: 'Former physical therapist assistant and 500-RYT yoga instructor dedicated to joint longevity, fascial decompression, and athletic mobility.',
    philosophy: 'You can only produce as much force as your joints can safely absorb. Mobility is your ultimate performance insurance.',
    certifications: ['RYT-500 Master Teacher', 'FRC (Functional Range Conditioning)', 'Anatomy Trains Specialist'],
    specialties: ['Mobility & Joint Longevity', 'Power Vinyasa Flow', 'Postural Restoration', 'Breathwork'],
    instagram: '@chloe_mobility_elite',
    classesTaught: ['Zen Flow Yoga', 'Athletic Mobility & Recovery'],
    availableSlots: [
      { day: 'Monday', times: ['07:30 AM', '09:00 AM', '06:00 PM'] },
      { day: 'Tuesday', times: ['07:00 AM', '08:30 AM', '05:00 PM'] },
      { day: 'Thursday', times: ['07:30 AM', '09:00 AM', '06:00 PM'] },
      { day: 'Sunday', times: ['08:00 AM', '10:00 AM', '11:30 AM'] },
    ],
  },
  {
    id: 'dev-patel',
    name: 'Dev Patel',
    role: 'Senior Bodybuilding & Hypertrophy Coach',
    experienceYears: 11,
    rating: 4.96,
    reviewCount: 198,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1200&q=80',
    bio: 'Men’s Physique national silver medalist with a science-based approach to mechanical tension, motor unit recruitment, and contest preparation.',
    philosophy: 'Hypertrophy is an engineering problem. Apply the correct stimulus, fuel the adaptation, and respect the recovery cycle.',
    certifications: ['IFBB Pro Academy Coach', 'ISSA Master Trainer', 'Mac-Nutrition Uni Certified'],
    specialties: ['Hypertrophy Science', 'Contest Prep', 'Body Recomposition', 'Nutritional Periodization'],
    instagram: '@dev_patel_physique',
    classesTaught: ['Iron & Hypertrophy'],
    availableSlots: [
      { day: 'Tuesday', times: ['08:00 AM', '11:00 AM', '04:00 PM', '07:00 PM'] },
      { day: 'Wednesday', times: ['09:00 AM', '12:00 PM', '05:00 PM', '08:00 PM'] },
      { day: 'Friday', times: ['08:00 AM', '11:00 AM', '04:00 PM'] },
      { day: 'Saturday', times: ['10:00 AM', '01:00 PM', '04:00 PM'] },
    ],
  },
  {
    id: 'sarah-jenkins',
    name: 'Sarah Jenkins',
    role: 'Metabolic & Female Athletic Lead',
    experienceYears: 6,
    rating: 4.94,
    reviewCount: 135,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    coverImage: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=1200&q=80',
    bio: 'Olympic lifting specialist and female physiology consultant empowering women to lift heavy, master the barbell, and conquer endurance barriers.',
    philosophy: 'Do not shrink yourself to fit a standard. Build a physique that commands space, power, and respect.',
    certifications: ['ACE-CPT', 'USAW Sports Performance Coach', 'Girls Gone Strong Coach'],
    specialties: ['Female Strength & Glute Lab', 'Metabolic Conditioning', 'Olympic Snatch/Clean', 'Cardio Programming'],
    instagram: '@sarah_jenkins_lift',
    classesTaught: ['HIIT Inferno', 'Functional Turf Conditioning'],
    availableSlots: [
      { day: 'Monday', times: ['08:00 AM', '10:00 AM', '05:30 PM'] },
      { day: 'Wednesday', times: ['07:30 AM', '09:30 AM', '06:00 PM'] },
      { day: 'Thursday', times: ['08:00 AM', '11:00 AM', '05:00 PM'] },
      { day: 'Saturday', times: ['09:30 AM', '11:30 AM', '03:00 PM'] },
    ],
  },
];

export const GYM_CLASSES: GymClass[] = [
  {
    id: 'class-01',
    title: 'HIIT Inferno',
    category: 'HIIT',
    trainerId: 'alex-morgan',
    trainerName: 'Alex Morgan',
    trainerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    trainerRole: 'Strength & Conditioning Coach',
    day: 'Monday',
    time: '06:00 PM',
    durationMinutes: 50,
    totalSeats: 20,
    bookedSeats: 18,
    intensity: 'Extreme',
    calorieBurn: '650-800 kcal',
    location: 'Studio A (Main Turf)',
    description: 'High-octane interval circuits combining Assault Bikes, curved treadmills, battle ropes, and kettlebell complexes to skyrocket metabolic burn.',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'class-02',
    title: 'Championship Boxing',
    category: 'Boxing',
    trainerId: 'elena-rostova',
    trainerName: 'Elena Rostova',
    trainerAvatar: 'https://images.unsplash.com/photo-1548690312-e3b507d8c110?auto=format&fit=crop&w=200&q=80',
    trainerRole: 'Master Boxing Coach',
    day: 'Monday',
    time: '07:30 PM',
    durationMinutes: 60,
    totalSeats: 16,
    bookedSeats: 14,
    intensity: 'High',
    calorieBurn: '600-750 kcal',
    location: 'Combat Ring & Bag Zone',
    description: 'Authentic 12-round boxing format featuring heavy-bag combinations, partner slip-rope drills, speed-bag timing, and core conditioning.',
    image: 'https://images.unsplash.com/photo-1549476464-37392f717541?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'class-03',
    title: 'Hyrox Athletic Prep',
    category: 'CrossFit',
    trainerId: 'marcus-vance',
    trainerName: 'Marcus Vance',
    trainerAvatar: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=200&q=80',
    trainerRole: 'CrossFit & Hyrox Lead',
    day: 'Tuesday',
    time: '06:30 AM',
    durationMinutes: 60,
    totalSeats: 24,
    bookedSeats: 22,
    intensity: 'Extreme',
    calorieBurn: '700-900 kcal',
    location: 'Turf Sprint Lane',
    description: 'Race-specific hybrid training targeting Sled Push, Sled Pull, Burpee Broad Jumps, Rowing, Farmers Carry, Sandbag Lunges, and Wall Balls.',
    image: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'class-04',
    title: 'Iron & Hypertrophy',
    category: 'Strength',
    trainerId: 'dev-patel',
    trainerName: 'Dev Patel',
    trainerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    trainerRole: 'Hypertrophy Coach',
    day: 'Tuesday',
    time: '05:30 PM',
    durationMinutes: 55,
    totalSeats: 15,
    bookedSeats: 12,
    intensity: 'High',
    calorieBurn: '450-600 kcal',
    location: 'Olympic Barbell Hall',
    description: 'Strict hypertrophy class utilizing mechanical drop sets, paused eccentric reps, and structured barbell/dumbbell overload for lean muscle mass.',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'class-05',
    title: 'Zen Flow Yoga',
    category: 'Yoga',
    trainerId: 'chloe-bennett',
    trainerName: 'Chloe Bennett',
    trainerAvatar: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=200&q=80',
    trainerRole: 'Mobility & Vinyasa Lead',
    day: 'Wednesday',
    time: '07:00 AM',
    durationMinutes: 50,
    totalSeats: 20,
    bookedSeats: 16,
    intensity: 'Medium',
    calorieBurn: '250-350 kcal',
    location: 'Mind & Body Studio B',
    description: 'Dynamic vinyasa flow with infrared heating at 28°C to open tight hips, enhance thoracic spine rotation, and regulate nervous system recovery.',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'class-06',
    title: 'Athletic Mobility & Recovery',
    category: 'Mobility',
    trainerId: 'chloe-bennett',
    trainerName: 'Chloe Bennett',
    trainerAvatar: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=200&q=80',
    trainerRole: 'Mobility & Vinyasa Lead',
    day: 'Thursday',
    time: '06:00 PM',
    durationMinutes: 45,
    totalSeats: 18,
    bookedSeats: 11,
    intensity: 'Medium',
    calorieBurn: '200-300 kcal',
    location: 'Recovery Suite',
    description: 'Decompress joints, release trigger points with foam rollers and hyperice guns, and restore functional range of motion for heavy lifts.',
    image: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'class-07',
    title: 'Functional Turf Conditioning',
    category: 'Functional',
    trainerId: 'sarah-jenkins',
    trainerName: 'Sarah Jenkins',
    trainerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    trainerRole: 'Metabolic & Female Athletic Lead',
    day: 'Friday',
    time: '06:00 PM',
    durationMinutes: 50,
    totalSeats: 20,
    bookedSeats: 19,
    intensity: 'High',
    calorieBurn: '550-700 kcal',
    location: 'Studio A (Main Turf)',
    description: 'Multi-planar agility ladders, sled relays, med ball slams, and plyometric boxes engineered to produce explosive athletic conditioning.',
    image: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'class-08',
    title: 'Weekend Gladiator Bootcamp',
    category: 'HIIT',
    trainerId: 'alex-morgan',
    trainerName: 'Alex Morgan',
    trainerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    trainerRole: 'Head of Strength & Conditioning',
    day: 'Saturday',
    time: '09:00 AM',
    durationMinutes: 60,
    totalSeats: 25,
    bookedSeats: 25,
    intensity: 'Extreme',
    calorieBurn: '750-900 kcal',
    location: 'Rooftop Turf Arena',
    description: 'The premier community showdown. Team-based challenges, tire flips, ski ergs, and heavy sled sprints. High energy, live DJ set.',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
  },
];

export const TRANSFORMATIONS: TransformationCase[] = [
  {
    id: 'trans-01',
    name: 'Rohan Sen',
    age: 32,
    occupation: 'Software Engineering Director',
    durationWeeks: 16,
    weightChangeKg: -14.5,
    bodyFatChangePercent: -12.4,
    beforeImage: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80',
    afterImage: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
    category: 'Fat Loss',
    trainerName: 'Alex Morgan',
    quote: 'EliteFit gave me back my athletic energy. I went from feeling sluggish at my desk to pulling a 180kg deadlift with zero lower back pain.',
    story: 'Working 12-hour desk shifts took a heavy toll on Rohan’s posture and energy. Joining the 1-on-1 coaching program, we structured a high-protein diet with a 4-day barbell split and weekly HIIT sessions. Within 16 weeks, he shed 14.5kg of visceral fat while adding visible lean muscle.',
    protocol: {
      training: '4-day Upper/Lower Strength Split + 2x HIIT Inferno',
      nutrition: '2,200 kcal high-protein (180g) carb-cycling protocol',
      frequency: '5 sessions / week',
    },
  },
  {
    id: 'trans-02',
    name: 'Pooja Bannerjee',
    age: 28,
    occupation: 'Corporate Lawyer',
    durationWeeks: 20,
    weightChangeKg: -8.0,
    bodyFatChangePercent: -9.8,
    beforeImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=600&q=80',
    afterImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80',
    category: 'Athletic Recomp',
    trainerName: 'Sarah Jenkins',
    quote: 'I used to starve myself with fad diets. EliteFit taught me that lifting heavy and eating to fuel performance is what truly transforms your physique.',
    story: 'Pooja wanted to build athletic definition without losing energy for high-pressure court cases. Under Sarah’s guidance, she embraced barbell squats, heavy hip thrusts, and boxing rounds, unlocking incredible core definition and mental resilience.',
    protocol: {
      training: 'Glute Lab + Barbell Strength + Boxing 2x/week',
      nutrition: 'Reverse dieted from 1200 kcal up to 1950 kcal nutrient dense',
      frequency: '4 sessions / week',
    },
  },
  {
    id: 'trans-03',
    name: 'Vikramaditya Roy',
    age: 39,
    occupation: 'Real Estate Developer',
    durationWeeks: 24,
    weightChangeKg: +6.2,
    bodyFatChangePercent: -5.5,
    beforeImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=600&q=80',
    afterImage: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=600&q=80',
    category: 'Muscle Gain',
    trainerName: 'Dev Patel',
    quote: 'At 39, people told me building significant muscle was past my prime. Dev and the EliteFit team proved them wrong with science and precision.',
    story: 'Vikram had been a skinny-fat lifter for years without making visible progress. We restructured his training to focus on high mechanical tension, paused reps, and an aggressive clean surplus. He gained 6.2kg of pure contractile tissue and added 40kg to his squat.',
    protocol: {
      training: 'Push/Pull/Legs Hypertrophy Rotation with RPE tracking',
      nutrition: '3,100 kcal clean surplus with high creatine & micronutrient balance',
      frequency: '5 sessions / week',
    },
  },
  {
    id: 'trans-04',
    name: 'Ananya Mukherjee',
    age: 26,
    occupation: 'Creative Director',
    durationWeeks: 12,
    weightChangeKg: -7.8,
    bodyFatChangePercent: -8.0,
    beforeImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    afterImage: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=600&q=80',
    category: 'Athletic Recomp',
    trainerName: 'Chloe Bennett',
    quote: 'Mobility combined with functional conditioning unlocked a level of athletic freedom I didn’t know existed.',
    story: 'Ananya suffered from severe desk-bound thoracic tightness and low stamina. A combined program of Power Vinyasa Yoga and Functional Turf conditioning transformed her stamina, mobility, and abdominal tone in just 3 months.',
    protocol: {
      training: '3x Functional Turf Conditioning + 2x Zen Flow Yoga',
      nutrition: 'Plant-forward whole foods with 130g protein goal',
      frequency: '5 sessions / week',
    },
  },
];

export const GYM_LOCATIONS: GymLocation[] = [
  {
    id: 'kolkata-flagship',
    city: 'Kolkata',
    name: 'Kolkata Flagship Club',
    address: '18/2 Park Street, 4th & 5th Floor, Kolkata, West Bengal 700016',
    landmark: 'Adjacent to Oxford Bookstore, Park Street Metro',
    phone: '+91 (033) 4001 8800',
    email: 'parkstreet@elitefit.club',
    hoursWeekday: '05:00 AM - 11:00 PM',
    hoursWeekend: '06:00 AM - 10:00 PM',
    image: 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=1000&q=80',
    mapEmbedUrl: 'https://maps.google.com/?q=Park+Street+Kolkata',
    facilities: [
      '18,000 sq ft Dual-Level Elite Arena',
      'Eleiko Olympic Lifting Platform Zone',
      'Curved Woodway Sprint Track',
      'Finnish Dry Sauna & Infrared Suite',
      'Cryotherapy & Cold Plunge Baths',
      'Organic Protein & Fuel Shake Bar',
      'Valet Parking & Executive Lockers',
    ],
    managerName: 'Arindam Ghosh',
    headTrainer: 'Alex Morgan',
  },
  {
    id: 'siliguri-centre',
    city: 'Siliguri',
    name: 'Siliguri City Centre Club',
    address: 'City Centre Mall, Level 3, Matigara, Siliguri, West Bengal 734010',
    landmark: 'Opposite Inox Multiplex, NH 31',
    phone: '+91 (0353) 257 9900',
    email: 'siliguri@elitefit.club',
    hoursWeekday: '05:30 AM - 10:30 PM',
    hoursWeekend: '06:00 AM - 09:30 PM',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1000&q=80',
    mapEmbedUrl: 'https://maps.google.com/?q=City+Centre+Siliguri',
    facilities: [
      '14,000 sq ft High-Altitude Conditioning Floor',
      'Championship Boxing Ring & Heavy Bags',
      'Hammer Strength Plate-Loaded Circuit',
      'Steam Spa & Hydrotherapy',
      'Locker Suites & Shake Bar',
    ],
    managerName: 'Suman Roy',
    headTrainer: 'Elena Rostova',
  },
  {
    id: 'durgapur-junction',
    city: 'Durgapur',
    name: 'Durgapur Junction Club',
    address: 'Junction Mall, 4th Floor, City Centre, Durgapur, West Bengal 713216',
    landmark: 'Near Durgapur Railway Junction Flyover',
    phone: '+91 (0343) 254 7700',
    email: 'durgapur@elitefit.club',
    hoursWeekday: '05:30 AM - 10:30 PM',
    hoursWeekend: '06:00 AM - 09:30 PM',
    image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?auto=format&fit=crop&w=1000&q=80',
    mapEmbedUrl: 'https://maps.google.com/?q=Junction+Mall+Durgapur',
    facilities: [
      '12,500 sq ft Strength & Hyrox Facility',
      'Olympic Barbell & Rogue Rig Station',
      'Functional AstroTurf Sprint Lanes',
      'Eucalyptus Steam Rooms',
      'Cardio Deck with Panoramic City Views',
    ],
    managerName: 'Subhajit Sen',
    headTrainer: 'Marcus Vance',
  },
  {
    id: 'asansol-gt',
    city: 'Asansol',
    name: 'Asansol Grand Club',
    address: 'Galaxy Mall, 3rd Floor, GT Road, Asansol, West Bengal 713303',
    landmark: 'Opposite Asansol Municipal Corporation',
    phone: '+91 (0341) 225 6600',
    email: 'asansol@elitefit.club',
    hoursWeekday: '05:30 AM - 10:30 PM',
    hoursWeekend: '06:00 AM - 09:30 PM',
    image: 'https://images.unsplash.com/photo-1593079831268-3381b0db4a77?auto=format&fit=crop&w=1000&q=80',
    mapEmbedUrl: 'https://maps.google.com/?q=Galaxy+Mall+Asansol',
    facilities: [
      '11,000 sq ft Powerlifting & Calisthenics Arena',
      'Full Range Free Weights (up to 60kg DBs)',
      'CrossFit Rig & Olympic Benches',
      'Dry Sauna & Luxury Showers',
      'Dedicated Yoga & Pilates Studio',
    ],
    managerName: 'Priyanka Dey',
    headTrainer: 'Dev Patel',
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    name: 'EliteFit Heavyweight Oversized Tee',
    category: 'Apparel',
    price: 1899,
    originalPrice: 2499,
    rating: 4.9,
    reviewCount: 88,
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    stockCount: 42,
    badge: 'BESTSELLER',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Onyx Black', 'Titanium Grey', 'Chalk White'],
    description: '280 GSM heavyweight custom combed cotton. Engineered drop-shoulder athletic cut designed to accentuate your upper frame during heavy training.',
    features: ['100% Organic Heavyweight Cotton (280 GSM)', 'Reinforced collar that never sags', 'Discreet high-density rubberized EliteFit chest badge', 'Pre-shrunk for zero post-wash distortion'],
  },
  {
    id: 'prod-02',
    name: 'EliteFit Matte Hydro-Flask (1000ml)',
    category: 'Accessories',
    price: 1299,
    originalPrice: 1799,
    rating: 4.8,
    reviewCount: 114,
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    stockCount: 65,
    badge: 'ESSENTIAL',
    colors: ['Matte Stealth Black', 'Electric Volt Green', 'Brushed Titanium'],
    description: 'Double-wall vacuum insulated surgical-grade 316 stainless steel. Keeps fluids ice-cold for 24 hours through your most brutal training sessions.',
    features: ['Surgical-grade 316 stainless steel interior', '24-hour cold / 12-hour hot insulation', 'Leakproof magnetic chug cap', 'BPA-free & condensation-free coating'],
  },
  {
    id: 'prod-03',
    name: 'Raw Grip Leather Lifting Straps',
    category: 'Gear',
    price: 999,
    originalPrice: 1499,
    rating: 5.0,
    reviewCount: 76,
    image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    stockCount: 28,
    badge: 'HEAVY DUTY',
    colors: ['Saddle Brown', 'Stealth Carbon'],
    description: '4mm top-grain buffalo leather engineered to lock your grip onto any knurling up to 400kg. Unbreakable tensile strength with neoprene wrist padding.',
    features: ['4mm top-grain buffalo hide leather', 'Tested up to 400kg max tensile pull', '6mm ergonomic neoprene wrist cushion', 'Becomes softer and more tactile over time'],
  },
  {
    id: 'prod-04',
    name: 'Elite Whey Isolate 100% (2kg)',
    category: 'Supplements',
    price: 4499,
    originalPrice: 5299,
    rating: 4.95,
    reviewCount: 156,
    image: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    stockCount: 35,
    badge: 'LAB TESTED',
    sizes: ['1kg (33 Servings)', '2kg (66 Servings)'],
    colors: ['Dark Belgian Chocolate', 'Vanilla Bourbon', 'Cafe Mocha'],
    description: 'Ultra-pure cross-flow microfiltered whey isolate delivering 27g protein, 6.2g BCAAs, and zero added sugars per scoop. Instant mixability with zero bloating.',
    features: ['27g 100% Whey Isolate per serving', 'DigeZyme enzyme complex for rapid digestion', 'Zero added sugar, zero filler gums', '3rd-party lab certified heavy metal free'],
  },
  {
    id: 'prod-05',
    name: 'Kinetic Heavy Resistance Loop Band Set',
    category: 'Gear',
    price: 1499,
    originalPrice: 1999,
    rating: 4.85,
    reviewCount: 62,
    image: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    stockCount: 50,
    colors: ['3-Band Pack (Light/Med/Heavy)'],
    description: 'Multi-layered natural Malaysian latex power bands for dynamic warmups, assisted pull-ups, banded barbell squats, and mobility decompression.',
    features: ['100% Natural Malaysian Latex', 'Snap-resistant continuous layered dipping', 'Resistance from 15kg to 65kg', 'Includes breathable mesh carry pouch'],
  },
  {
    id: 'prod-06',
    name: 'Elite Tactical Duffel Gym Bag (45L)',
    category: 'Accessories',
    price: 3299,
    originalPrice: 4299,
    rating: 4.9,
    reviewCount: 43,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=600&q=80',
    inStock: true,
    stockCount: 19,
    badge: 'WATERPROOF',
    colors: ['Military Carbon', 'Stealth Black'],
    description: 'Military-grade 1000D Cordura nylon with separate ventilated shoe tunnel, waterproof wet-towel compartment, and padded 16-inch laptop sleeve.',
    features: ['1000D ballistic Cordura water-repellent shell', 'Dedicated ventilated shoe compartment (fits up to UK 13)', 'Thermal shaker bottle pocket', 'Heavy-duty YKK matte black zippers'],
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-01',
    name: 'Rahul Sharma',
    phone: '+91 98305 67890',
    email: 'rahul.s@outlook.com',
    preferredLocation: 'Kolkata Flagship (Park Street)',
    preferredDate: '2026-09-21',
    fitnessGoal: 'Lose 12kg fat & build functional stamina',
    stage: 'NEW',
    source: 'Website Trial',
    createdAt: '2026-09-19T10:30:00Z',
    notes: 'Inquired about personal training and evening HIIT slots.',
  },
  {
    id: 'lead-02',
    name: 'Sneha Roy',
    phone: '+91 98311 44556',
    email: 'sneha.roy@gmail.com',
    preferredLocation: 'Siliguri City Centre Club',
    preferredDate: '2026-09-22',
    fitnessGoal: 'Boxing conditioning & core strength',
    stage: 'CONTACTED',
    source: 'WhatsApp Direct',
    createdAt: '2026-09-18T16:15:00Z',
    notes: 'Spoke with front desk. Interested in Elena Rostova boxing classes.',
  },
  {
    id: 'lead-03',
    name: 'Amitabh Sen',
    phone: '+91 98322 99887',
    email: 'amitabh.sen@corp.in',
    preferredLocation: 'Durgapur Junction Club',
    preferredDate: '2026-09-20',
    fitnessGoal: 'Muscle hypertrophy & bench press PR',
    stage: 'TRIAL BOOKED',
    source: 'Website Trial',
    createdAt: '2026-09-18T11:00:00Z',
    notes: 'Trial session confirmed with Coach Dev Patel for Sunday 10am.',
  },
  {
    id: 'lead-04',
    name: 'Ritika Ganguly',
    phone: '+91 98333 11224',
    email: 'ritika.g@fintech.co',
    preferredLocation: 'Kolkata Flagship (Park Street)',
    preferredDate: '2026-09-17',
    fitnessGoal: 'Rehab posture & join yoga/mobility',
    stage: 'CONVERTED',
    source: 'Referral',
    createdAt: '2026-09-15T09:20:00Z',
    notes: 'Enrolled in Annual PRO Membership! Assigned to Chloe Bennett.',
  },
  {
    id: 'lead-05',
    name: 'Karan Mehra',
    phone: '+91 98344 77889',
    email: 'karan.m@gmail.com',
    preferredLocation: 'Asansol Grand Club',
    preferredDate: '2026-09-23',
    fitnessGoal: 'Hyrox preparation & cardiovascular threshold',
    stage: 'NEW',
    source: 'Website Trial',
    createdAt: '2026-09-19T14:45:00Z',
    notes: 'Requested call back after 6 PM.',
  },
];

export const INITIAL_PR_RECORDS: PRRecord[] = [
  { id: 'pr-1', exercise: 'Conventional Deadlift', weight: 190, unit: 'kg', reps: 1, date: '2026-09-12', previousRecord: 180 },
  { id: 'pr-2', exercise: 'Barbell Back Squat', weight: 155, unit: 'kg', reps: 3, date: '2026-09-08', previousRecord: 145 },
  { id: 'pr-3', exercise: 'Barbell Flat Bench Press', weight: 115, unit: 'kg', reps: 2, date: '2026-09-02', previousRecord: 110 },
  { id: 'pr-4', exercise: 'Standing Overhead Barbell Press', weight: 75, unit: 'kg', reps: 5, date: '2026-08-25', previousRecord: 70 },
  { id: 'pr-5', exercise: 'Weighted Pull-Up (+25kg)', weight: 105, unit: 'kg', reps: 6, date: '2026-08-19', previousRecord: 100 },
];

export const WEIGHT_HISTORY: WeightLog[] = [
  { date: 'Jul 01', weight: 84.5, bodyFat: 18.2 },
  { date: 'Jul 15', weight: 83.8, bodyFat: 17.6 },
  { date: 'Aug 01', weight: 82.9, bodyFat: 16.9 },
  { date: 'Aug 15', weight: 82.1, bodyFat: 16.2 },
  { date: 'Sep 01', weight: 81.3, bodyFat: 15.4 },
  { date: 'Sep 15', weight: 80.6, bodyFat: 14.8 },
  { date: 'Sep 19', weight: 80.2, bodyFat: 14.5 },
];

export const INITIAL_BOOKINGS: ClassBooking[] = [
  {
    id: 'bk-01',
    classId: 'class-01',
    className: 'HIIT Inferno',
    category: 'HIIT',
    trainerName: 'Alex Morgan',
    date: 'Today',
    time: '06:00 PM',
    location: 'Studio A (Main Turf)',
    status: 'Upcoming',
    bookedAt: '2026-09-18T14:20:00Z',
    qrCheckinCode: 'EF-CHK-8819',
  },
  {
    id: 'bk-02',
    classId: 'class-03',
    className: 'Hyrox Athletic Prep',
    category: 'CrossFit',
    trainerName: 'Marcus Vance',
    date: 'Tomorrow',
    time: '06:30 AM',
    location: 'Turf Sprint Lane',
    status: 'Upcoming',
    bookedAt: '2026-09-19T08:15:00Z',
    qrCheckinCode: 'EF-CHK-9102',
  },
  {
    id: 'bk-03',
    classId: 'class-02',
    className: 'Championship Boxing',
    category: 'Boxing',
    trainerName: 'Elena Rostova',
    date: '2026-09-16',
    time: '07:30 PM',
    location: 'Combat Ring & Bag Zone',
    status: 'Completed',
    bookedAt: '2026-09-15T10:00:00Z',
    qrCheckinCode: 'EF-CHK-7741',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    title: 'Upcoming Class Reminder',
    message: 'Your HIIT Inferno session with Alex Morgan starts at 06:00 PM today. Studio A.',
    type: 'booking',
    timestamp: '2 hours ago',
    read: false,
    actionUrl: '/dashboard/bookings',
  },
  {
    id: 'notif-02',
    title: 'New PR Logged!',
    message: 'Congratulations! You broke your Deadlift record with a massive 190kg pull.',
    type: 'achievement',
    timestamp: 'Yesterday',
    read: false,
    actionUrl: '/dashboard/progress',
  },
  {
    id: 'notif-03',
    title: 'Elite Club Privilege Active',
    message: 'Your bi-weekly 1-on-1 PT consultation window is now open. Choose your preferred coach.',
    type: 'membership',
    timestamp: '3 days ago',
    read: true,
    actionUrl: '/trainers',
  },
];

export const ADMIN_ANALYTICS = {
  totalMembers: 1284,
  activeMembers: 1106,
  monthlyRevenue: 842000,
  monthlyRevenueFormatted: '₹8.42L',
  bookingsThisMonth: 342,
  newLeadsCount: 87,
  liveOccupancyPercent: 68,
  liveOccupancyCount: 142,
  revenueChart: [
    { month: 'Apr', revenue: 640000, target: 600000 },
    { month: 'May', revenue: 690000, target: 650000 },
    { month: 'Jun', revenue: 720000, target: 700000 },
    { month: 'Jul', revenue: 780000, target: 750000 },
    { month: 'Aug', revenue: 810000, target: 800000 },
    { month: 'Sep', revenue: 842000, target: 820000 },
  ],
  membershipGrowth: [
    { month: 'Apr', members: 920 },
    { month: 'May', members: 1010 },
    { month: 'Jun', members: 1080 },
    { month: 'Jul', members: 1150 },
    { month: 'Aug', members: 1220 },
    { month: 'Sep', members: 1284 },
  ],
  classPopularity: [
    { name: 'HIIT Inferno', attendees: 380, fillRate: 94 },
    { name: 'Boxing', attendees: 310, fillRate: 91 },
    { name: 'Hyrox Prep', attendees: 290, fillRate: 96 },
    { name: 'Iron Hypertrophy', attendees: 270, fillRate: 88 },
    { name: 'Zen Flow Yoga', attendees: 240, fillRate: 82 },
    { name: 'Mobility & Recovery', attendees: 180, fillRate: 75 },
  ],
  checkinHourlyHeatmap: [
    { hour: '06 AM', checkins: 85 },
    { hour: '07 AM', checkins: 130 },
    { hour: '08 AM', checkins: 110 },
    { hour: '09 AM', checkins: 70 },
    { hour: '12 PM', checkins: 45 },
    { hour: '04 PM', checkins: 65 },
    { hour: '05 PM', checkins: 120 },
    { hour: '06 PM', checkins: 165 },
    { hour: '07 PM', checkins: 180 },
    { hour: '08 PM', checkins: 145 },
    { hour: '09 PM', checkins: 80 },
  ],
};
